name: VISUALVOCAL01
favicon: null
layout_spectrum: 0
typography_spectrum: 0.83848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9157965877093375
  lightness: 0.2724682956468314
  saturation: 0.934061964508146
  rhythmicContrast: 0.9992761558387429
purpose: []
